### PR TITLE
Add html ids and classes to systemdata.htm output

### PR DESCRIPTION
**Pull request by addshore**
This makes selecting the channel member count based
on the channel name a bit easier!

Note: actual output has not actually been tested with this change but I expect it to work!

### CODE REVIEW

**Comment by addshore** [comment]
It might make more sense just to dump all of the info on this page into json too? :)

**Comment by addshore** [comment]
When will this be deployed? :)

**Comment by benapetr** [comment]
when someone ssh to wm-bot and do

cd /mnt/share/wikimedia-bot
sudo git pull
cd /mnt/share/wm-bot and run
sudo ./easydeploy.sh

**Comment by addshore** [comment]
https://wikitech.wikimedia.org/w/index.php?title=Nova_Resource:Bots/SAL&diff=198889&oldid=174223

**Pull request merged**
